version: "2"
services:
  postgre:
    image: postgres:11
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: "m@0dl3ing"
      POSTGRES_DB: moodle
    networks:
      - default
  moodle:
    image: moodlehq/moodle-php-apache:8.0
    environment:
      MOODLE_DOCKER_DBTYPE: pgsql
      MOODLE_DOCKER_DBNAME: moodle
      MOODLE_DOCKER_DBUSER: moodle
      MOODLE_DOCKER_DBPASS: "m@0dl3ing"
      MOODLE_DOCKER_BROWSER: firefox
    user: "www-data:www-data"
    ports:
      - "8080:80"
    depends_on:
      - postgre
    networks:
      - default

  dockerize:
    image: jwilder/dockerize
