version: "3.2"
services:
  cypress:
    image: "cypress/included:10.11.0"
    entrypoint: cypress
    env_file:
      - env.d/cypress
    environment:
      - DISPLAY=${DISPLAY}
    working_dir: /e2e
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
      - ./e2e:/e2e
      - /tmp/.X11-unix:/tmp/.X11-unix

  node:
    image: circleci/node:16
    working_dir: /app
    user: ${DOCKER_UID}:${DOCKER_GID}
    volumes:
      - .:/app

  ffmpeg:
    image: "jrottenberg/ffmpeg:5.1-alpine"
    volumes:
      - ./e2e:/e2e
