version: "2"
services:
  moodle_postgre:
    image: postgres:13.3
    env_file: env.d/moodle
    networks:
      default:

  moodle:
    image: moodlehq/moodle-php-apache:8.0
    env_file: env.d/moodle
    user: "www-data:www-data"
    ports:
      - "8080:80"
    depends_on:
      - moodle_postgre
    networks:
      default:

  dockerize:
    image: jwilder/dockerize
